sudo: required
services:
  - docker
before_install:
  - docker build -t dmitrybunin/udemy-complex-client-test -f ./client/Dockerfile.dev ./client
script:
  # -- --coverage makes 'npm run test' exit (with status 0) once the test run is finished
  # istead of waiting for user input
  - docker run -e CI=true dmitrybunin/udemy-complex-test npm run test -- --coverage 
after_success:
  - docker build -t dmitrybunin/udemy-complex-client-prod ./client
  - docker build -t dmitrybunin/udemy-complex-nginx-prod ./nginx
  - docker build -t dmitrybunin/udemy-complex-server-prod ./server
  - docker build -t dmitrybunin/udemy-complex-worker-prod ./worker
  # Log into Docker CLI
  # Takes input (env_var) and emmits it into
  - echo "$DOCKER_PASSWORD" | docker login -u "$DMITRY_ID" --password-stdin
  # Push the above production images to DockerHub
  - docker push dmitrybunin/udemy-complex-client-prod
  - docker push dmitrybunin/udemy-complex-nginx-prod
  - docker push dmitrybunin/udemy-complex-server-prod
  - docker push dmitrybunin/udemy-complex-worker-prod