version: '3'
services:
  postgres:
    image: postgres:latest
  
  redis:
    image: redis:latest
  
  nginx: # router
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'
  
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules # leave this directory inside the container alone, don't map it to the outside
      - ./server:/app # map /app inside the container to ./server outside the container
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  
  frontend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules # leave this directory inside the container alone, don't map it to the outside
      - ./client:/app # map /app inside the container to ./server outside the container
  
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules # leave this directory inside the container alone, don't map it to the outside
      - ./worker:/app # map /app inside the container to ./server outside the container  
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379

